-- DROP TABLESPACE
DROP TABLESPACE TESTE_DATA_128K
INCLUDING CONTENTS
CASCADE CONSTRAINTS;
DROP TABLESPACE TESTE_INDX_128K
INCLUDING CONTENTS
CASCADE CONSTRAINTS;
-- CREATE TABLESPACE
create tablespace TESTE_DATA_128K datafile 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\TESTE_DATA_128K01.dbf'  size 500m autoextend on next 200m maxsize 32000m;
create tablespace TESTE_INDX_128K datafile 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\TESTE_INDX_128K01.dbf'  size 500m autoextend on next 200m maxsize 32000m;

-- DROP USER
drop user "USR_TESTE" CASCADE;

-- CREATE USER
create user "USR_TESTE" identified by TESTE;

-- USER SQL
ALTER USER "USR_TESTE"
DEFAULT TABLESPACE "TESTE_DATA_128K"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "USR_TESTE" QUOTA UNLIMITED ON TESTE_DATA_128K;
ALTER USER "USR_TESTE" QUOTA UNLIMITED ON TESTE_INDX_128K;

-- ROLES
grant connect,resource,dba to USR_TESTE;
grant all PRIVILEGES TO USR_TESTE;
grant sysdba to USR_TESTE;

-- SYSTEM PRIVILEGES
grant all PRIVILEGES TO USR_TESTE;

commit;
